from enum import Enum

class SessionStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"

class EventSource(str, Enum):
    SYSMON = "SYSMON"
    PROCMON = "PROCMON"
    WIRESHARK = "WIRESHARK"
    AGENT = "AGENT"
    ADAM = "ADAM"
    VMI = "VMI"
    AMTD = "AMTD"

class EventCategory(str, Enum):
    PROCESS = "PROCESS"
    FILE = "FILE"
    REGISTRY = "REGISTRY"
    NETWORK = "NETWORK"
    MODULE = "MODULE"
    WMI = "WMI"
    MUTATION = "MUTATION"
    SYSTEM = "SYSTEM"
    VMI_TRAP = "VMI_TRAP"
    AMTD_MUTATION = "AMTD_MUTATION"

class PolicyVerdict(str, Enum):
    EXECUTE = "EXECUTE"
    SUPPRESSED_BUDGET = "SUPPRESSED_BUDGET"
    SUPPRESSED_COOLDOWN = "SUPPRESSED_COOLDOWN"
    SUPPRESSED_CONFIDENCE = "SUPPRESSED_CONFIDENCE"
    SUPPRESSED_CONFLICT = "SUPPRESSED_CONFLICT"
    DRY_RUN = "DRY_RUN"

class MutationStatus(str, Enum):
    APPLIED = "APPLIED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    REVERTED = "REVERTED"
    SKIPPED = "SKIPPED"

class DeceptionArm(str, Enum):
    CONTROL = "CONTROL"
    TREATMENT = "TREATMENT"

class NetworkMode(str, Enum):
    HOST_ONLY = "HOST_ONLY"
    SIMULATED = "SIMULATED"
    INTERNET = "INTERNET"
