from typing import Protocol, AsyncIterator, Any
from adam.contracts.raw_event import RawEvent
from adam.contracts.semantic_event import SemanticEvent
from adam.contracts.policy_decision import PolicyDecision
from adam.contracts.mutation import MutationResult

class ISandboxController(Protocol):
    async def prepare(self) -> None: ...
    async def detonate(self, sample_path: str) -> None: ...
    async def apply_mutation(self, decision: PolicyDecision) -> MutationResult: ...
    async def collect_artifacts(self) -> None: ...
    async def teardown(self) -> None: ...

class ICollector(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def iter_events(self) -> AsyncIterator[RawEvent]: ...

class IFusionEngine(Protocol):
    async def ingest(self, event: RawEvent) -> list[SemanticEvent]: ...

class IPolicyEngine(Protocol):
    async def evaluate(self, event: SemanticEvent, context: Any) -> list[PolicyDecision]: ...

class IDeceptionEngine(Protocol):
    async def execute(self, decision: PolicyDecision) -> MutationResult: ...
