class NetworkLures:
    PRIMITIVES = [
        "MOUNT_FAKE_NETWORK_SHARE",
        "SYNTHESIZE_NETWORK_TOPOLOGY",
        "SYNTHESIZE_RDP_TARGETS",
        "SYNTHESIZE_REMOTE_HOSTS",
        "SYNTHESIZE_DOMAIN_TOPOLOGY",
        "FABRICATE_C2_RESPONSE",
        "ACTIVATE_C2_SINKHOLE"
    ]
