class RegistryLures:
    PRIMITIVES = [
        "SPAWN_FAKE_DC_ARTIFACTS",
        "SIMULATE_AV_PRESENCE",
        "SPOOF_HARDWARE_IDENTITY",
        "HIDE_VM_ARTIFACTS",
        "SPOOF_HOST_IDENTITY",
        "SPOOF_DOMAIN_MEMBERSHIP",
        "SYNTHESIZE_SOFTWARE_INVENTORY",
        "SPOOF_SECURITY_CONFIGURATION",
        "SPOOF_FIREWALL_STATE",
        "SIMULATE_AMSI_TARGET",
        "SIMULATE_SECURITY_CONFIGURATION",
        "SPOOF_PARENT_PROCESS",
        "SPOOF_DEBUGGER_STATE",
        "HIDE_ANALYSIS_ARTIFACTS",
        "TRIGGER_USER_SIMULATION",
        "NORMALIZE_TIMING",
        "SYNTHESIZE_USER_PROFILE",
        "SYNTHESIZE_VPN_PROFILE"
    ]
